# SPDX-License-Identifier: Apache-2.0
---

- name: Ansible Task block for looped provisioning of KubeVirt Virtual Machines
  any_errors_fatal: true
  block:

    - name: SAP VM Provision - KubeVirt - Provision hosts to KubeVirt
      ansible.builtin.include_tasks:
        file: "{{ __sap_vm_provision_task_file }}/execute_provision.yml"

    - name: SAP VM Provision - KubeVirt - Add hosts provisioned to the Ansible Inventory
      ansible.builtin.add_host:
        name: "{{ add_item[0].host_node }}"
        groups: "{{ add_item[0].sap_system_type + '_' if (add_item[0].sap_system_type != '') }}{{ add_item[0].sap_host_type }}"
        ansible_host: "{{ add_item[0].__sap_vm_provision_fact_private_ip }}"
        ansible_user: "{{ sap_vm_provision_kubevirt_vm_os_user }}"
      loop: "{{ ansible_play_hosts | map('extract', hostvars, '__sap_vm_provision_fact_provisioned_hosts') }}"
      loop_control:
        label: "{{ add_item[0].host_node }}"
        loop_var: add_item
      register: __sap_vm_provision_register_provision_host_all_add


    - name: SAP VM Provision - KubeVirt - Set fact to hold all inventory hosts in all groups
      ansible.builtin.set_fact:
        __sap_vm_provision_fact_merged_hosts_list: "{{
            [[groups[sap_vm_provision_group_hana_primary] | d([])],
            [groups[sap_vm_provision_group_hana_secondary] | d([])],
            [groups[sap_vm_provision_group_anydb_primary] | d([])],
            [groups[sap_vm_provision_group_anydb_secondary] | d([])],
            [groups[sap_vm_provision_group_nwas_ascs] | d([])],
            [groups[sap_vm_provision_group_nwas_ers] | d([])],
            [groups[sap_vm_provision_group_nwas_pas] | d([])],
            [groups[sap_vm_provision_group_nwas_aas] | d([])]] | flatten | select() }}"

    - name: SAP VM Provision - KubeVirt - Identify hosts
      ansible.builtin.include_tasks:
        file: common/identify_hosts.yml

    - name: SAP VM Provision - KubeVirt - Set Ansible Vars
      ansible.builtin.include_tasks:
        file: common/set_ansible_vars.yml

  rescue:
    # This requires no_log set on each Ansible Task, and not set on the Ansible Task Block
    # This requires an Ansible Task Block containing the Ansible Tasks for calling
    # Infrastructure Platform APIs (via Ansible Modules)
    - name: SAP VM Provision - KubeVirt - Show errors in task outputs
      ansible.builtin.fail:
        msg: "{{ lookup('ansible.builtin.vars', loop_item) }}"
      loop:
        # Main
        - __sap_vm_provision_register_provision_host_all_add
        # Provision
        - __sap_vm_provision_task_provision_host_single
        - __sap_vm_provision_task_provision_host_single_info
      loop_control:
        loop_var: loop_item
        index_var: loop_item_index
        label: "{{ 'Variable No. ' + (loop_item_index | string) }}"
      when:
        - lookup('ansible.builtin.vars', loop_item, default='') | length > 0
        - not lookup('ansible.builtin.vars', loop_item, default='') is skipped
        - lookup('ansible.builtin.vars', loop_item, default='') is failed

    - name: SAP VM Provision - KubeVirt - Fail if provisioning failed
      ansible.builtin.fail:
        msg: |
          FAIL: Provisioning has failed during one of tasks not producing registered output.
          You can investigate failure in tasks above or by:
          - Increasing verbosity
          - Setting the variable '__sap_vm_provision_no_log' to 'false'


- name: Ansible Task block to execute on target inventory hosts
  remote_user: "{{ sap_vm_provision_kubevirt_vm_os_user }}"
  become: true
  become_user: root
  delegate_to: "{{ inventory_hostname }}"
  vars:
    ansible_ssh_private_key_file: "{{ sap_vm_provision_ssh_host_private_key_file_path }}"
    ansible_ssh_common_args: >-
      {{ sap_vm_provision_ssh_host_ssh_args }}
      -o ProxyJump={{ sap_vm_provision_kubevirt_vm_execution_host_user }}@{{ sap_vm_provision_execution_host }}
  block:

    # Required to collect the remote host's facts for further processing in the following steps.
    # Collected facts can be used for all conditional tasks on provisioned hosts like ansible_facts['os_family'].
    - name: SAP VM Provision - KubeVirt - Gather host facts
      ansible.builtin.setup:

    # Must be set to short hostname,
    # so that command 'hostname' and 'hostname -s' return the short hostname only;
    # otherwise may cause error with SAP SWPM using name.domain.com.domain.com
    - name: SAP VM Provision - KubeVirt - Change system hostname (must be set to short name and not FQDN, as required by SAP)
      ansible.builtin.hostname:
        name: "{{ inventory_hostname_short }}"

    - name: SAP VM Provision - KubeVirt - Set /etc/hosts
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts.yml

    - name: SAP VM Provision - KubeVirt - Set /etc/hosts for HA
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts_ha.yml
      when:
        - __sap_vm_provision_fact_is_ha_hana or __sap_vm_provision_fact_is_ha_anydb or __sap_vm_provision_fact_is_ha_nwas_ers

    - name: SAP VM Provision - KubeVirt - Set /etc/hosts for Scale-Out
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts_scaleout.yml
      when: __sap_vm_provision_fact_is_hana_scaleout

    - name: SAP VM Provision - KubeVirt - Set vars for sap_storage_setup Ansible Role
      ansible.builtin.include_tasks:
        file: common/set_ansible_vars_storage.yml

    - name: SAP VM Provision - KubeVirt - Register Web Forward Proxy
      ansible.builtin.include_tasks:
        file: common/register_proxy.yml

    - name: SAP VM Provision - KubeVirt - Register Package Repositories
      ansible.builtin.include_tasks:
        file: common/register_os.yml
