# SPDX-License-Identifier: Apache-2.0
---

#### Validate required variables for specific 'sap_vm_provision_iac_platform ####

- name: Assert that string variables are valid for {{ sap_vm_provision_iac_platform }}
  ansible.builtin.assert:
    that:
      - lookup('ansible.builtin.vars', assert_item, default='__UNDEFINED_VARIABLE_DETECTED') != '__UNDEFINED_VARIABLE_DETECTED'
      - lookup('ansible.builtin.vars', assert_item) is string
      - lookup('ansible.builtin.vars', assert_item) | trim | length > 0
    fail_msg: |
      {% if lookup('ansible.builtin.vars', assert_item, default='__UNDEFINED_VARIABLE_DETECTED') == '__UNDEFINED_VARIABLE_DETECTED' %}
        The variable '{{ assert_item }}' is undefined.
      {% elif lookup('ansible.builtin.vars', assert_item) is not string %}
        The variable '{{ assert_item }}' is not a String.
      {% else %}
        The variable '{{ assert_item }}' is empty.
      {% endif %}
  loop:
    - sap_vm_provision_ibmpowervm_vc_auth_endpoint
    - sap_vm_provision_ibmpowervm_vc_user
    - sap_vm_provision_ibmpowervm_vc_user_password
    - sap_vm_provision_ibmpowervm_vc_project_name
    - sap_vm_provision_ibmpowervm_host_group_name
    - sap_vm_provision_ibmpowervm_host_group_shared_procesor_pool_name
    - sap_vm_provision_ibmpowervm_network_name
    - sap_vm_provision_ibmpowervm_network_vnic_type
    - sap_vm_provision_ibmpowervm_storage_template_name
    - sap_vm_provision_ibmpowervm_placement_resource_name
    - sap_vm_provision_ibmpowervm_vm_host_os_image
  loop_control:
    loop_var: assert_item


- name: Assert that string variables are valid for {{ sap_vm_provision_iac_platform }} using 'ansible'
  ansible.builtin.assert:
    that:
      - lookup('ansible.builtin.vars', assert_item, default='__UNDEFINED_VARIABLE_DETECTED') != '__UNDEFINED_VARIABLE_DETECTED'
      - lookup('ansible.builtin.vars', assert_item) is string
      - lookup('ansible.builtin.vars', assert_item) | trim | length > 0
    fail_msg: |
      {% if lookup('ansible.builtin.vars', assert_item, default='__UNDEFINED_VARIABLE_DETECTED') == '__UNDEFINED_VARIABLE_DETECTED' %}
        The variable '{{ assert_item }}' is undefined.
      {% elif lookup('ansible.builtin.vars', assert_item) is not string %}
        The variable '{{ assert_item }}' is not a String.
      {% else %}
        The variable '{{ assert_item }}' is empty.
      {% endif %}
  loop:
    - sap_vm_provision_ibmpowervm_key_pair_name_ssh_host_public_key
    - sap_vm_provision_ssh_host_public_key_file_path
  loop_control:
    loop_var: assert_item
  when:
    - sap_vm_provision_iac_type == 'ansible'


- name: Assert that boolean variables are valid for {{ sap_vm_provision_iac_platform }}
  ansible.builtin.assert:
    that:
      - lookup('ansible.builtin.vars', assert_item, default='__UNDEFINED_VARIABLE_DETECTED') != '__UNDEFINED_VARIABLE_DETECTED'
      - lookup('ansible.builtin.vars', assert_item) is boolean
      - lookup('ansible.builtin.vars', assert_item) | trim | length > 0
    fail_msg: |
      {% if lookup('ansible.builtin.vars', assert_item, default='__UNDEFINED_VARIABLE_DETECTED') == '__UNDEFINED_VARIABLE_DETECTED' %}
        The variable '{{ assert_item }}' is undefined.
      {% elif lookup('ansible.builtin.vars', assert_item) is not boolean %}
        The variable '{{ assert_item }}' is not a Boolean.
      {% else %}
        The variable '{{ assert_item }}' is empty.
      {% endif %}
  loop:
    - sap_vm_provision_ibmpowervm_placement_strategy_spread
  loop_control:
    loop_var: assert_item


- name: Assert that all platform specific keys are defined in the specification plan for all hosts
  ansible.builtin.assert:
    that:
      - __host_specification_plan.values() | selectattr(__platform_specific_key, 'defined') | list | length == __host_specification_plan | length
    fail_msg: >-
      One or more host entries in plan '{{ sap_vm_provision_host_specification_plan }}'
      under dictionary '{{ __sap_vm_provision_host_spec_dict_name }}' are missing the mandatory '{{ __platform_specific_key }}' key.
  loop:
    - 'ibmpowervm_vm_cpu_threads'
    - 'ibmpowervm_vm_memory_gib'
    - 'ibmpowervm_vm_cpu_smt'
  loop_control:
    loop_var: __platform_specific_key
  vars:
    __host_specification_plan: "{{ lookup('vars', __sap_vm_provision_host_spec_dict_name)[sap_vm_provision_host_specification_plan] }}"
