# SPDX-License-Identifier: Apache-2.0
---

- name: Ansible Task block for Terraform apply of multiple Terraform Modules
  block:

    # Do not use ansible.builtin.copy as this will cause error 'not writable' on localhost (even if user has permissions)
    # Should not cause overwrite of Terraform State files, but should overwrite populated Terraform Template files if they are updated
    - name: SAP VM Provision - AWS - Copy Terraform Template files to provided working directory path
      ansible.builtin.shell:
        cmd: |
          mkdir -p {{ sap_vm_provision_terraform_work_dir_path }}
          cp -R {{ role_path }}/tasks/platform_ansible_to_terraform/{{ sap_vm_provision_iac_platform }}/tf_template/* \
            {{ sap_vm_provision_terraform_work_dir_path }}
      run_once: true
      changed_when: true

    - name: SAP VM Provision - AWS - Terraform Template for SAP - AWS
      environment:
        AWS_ACCESS_KEY_ID: "{{ sap_vm_provision_aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ sap_vm_provision_aws_secret_access_key }}"
        AWS_REGION: "{{ sap_vm_provision_aws_region }}"
      cloud.terraform.terraform:
        project_path: "{{ sap_vm_provision_terraform_work_dir_path }}"
        state: "{{ sap_vm_provision_terraform_state }}"
        force_init: true
        complex_vars: true
        variables:
          aws_access_key: "{{ sap_vm_provision_aws_access_key }}"
          aws_secret_key: "{{ sap_vm_provision_aws_secret_access_key }}"
          aws_vpc_availability_zone: "{{ sap_vm_provision_aws_vpc_availability_zone }}"
          aws_vpc_subnet_id: "{{ sap_vm_provision_aws_vpc_subnet_id }}"
          sap_vm_provision_resource_prefix: "{{ sap_vm_provision_resource_prefix }}"
          sap_vm_provision_dns_root_domain: "{{ sap_vm_provision_dns_root_domain }}"
          sap_vm_provision_bastion_os_image: "{{ sap_vm_provision_bastion_os_image }}"
          sap_vm_provision_bastion_user: "{{ sap_vm_provision_bastion_user }}"
          sap_vm_provision_bastion_ssh_port: "{{ sap_vm_provision_bastion_ssh_port }}"
          map_os_image_regex: "{{ lookup('ansible.builtin.vars', __sap_vm_provision_host_image_dict_name) }}"
          map_host_specifications: "{{ lookup('ansible.builtin.vars', __sap_vm_provision_host_spec_dict_name) }}"
          sap_vm_provision_host_specification_plan: "{{ sap_vm_provision_host_specification_plan }}"
          sap_vm_provision_aws_ec2_vs_host_os_image: "{{ sap_vm_provision_aws_ec2_vs_host_os_image }}"
          sap_install_media_detect_source_directory: "{{ sap_install_media_detect_source_directory }}"
          sap_hana_install_instance_nr: "{{ sap_hana_install_instance_nr | default('') }}"
          sap_nwas_abap_ascs_instance_no: "{{ sap_swpm_ascs_instance_nr | default('') }}"
          sap_nwas_abap_pas_instance_no: "{{ sap_swpm_pas_instance_nr | default('') }}"
      register: __sap_vm_provision_register_terraform_template1_result
      no_log: "{{ __sap_vm_provision_no_log }}"
      run_once: true

    - name: SAP VM Provision - AWS - Terraform Template output
      ansible.builtin.debug:
        var: __sap_vm_provision_register_terraform_template1_result
      run_once: true


    # - name: SAP VM Provision - AWS - Execute Ansible Role cloud.terraform.inventory_from_outputs
    #   register: terraform_output_to_ansible_inventory
    #   ansible.builtin.include_role:
    #     name: cloud.terraform.inventory_from_outputs
    #   vars:
    #     project_path: "{{ sap_vm_provision_terraform_work_dir_path }}"
    #     mapping_variables:
    #       host_list: sap_host_list
    #       name: output_host_name
    #       ip: output_host_ip
    #       user: output_host_os_user
    #       group: output_ansible_inventory_group


    - name: SAP VM Provision - AWS - Read outputs from project path
      cloud.terraform.terraform_output:
        project_path: "{{ sap_vm_provision_terraform_work_dir_path }}"
      register: __sap_vm_provision_register_terraform_output_project_path
      no_log: "{{ __sap_vm_provision_no_log }}"
      run_once: true
      when: sap_vm_provision_terraform_state == "present"

    - name: SAP VM Provision - AWS - Add hosts from terraform_output to the group defined in terraform_output
      ansible.builtin.add_host:
        name: "{{ host_item['output_host_name'] }}"
        groups: "{{ host_item['output_ansible_inventory_group'] }}"
        ansible_host: "{{ host_item['output_host_ip'] }}"
        ansible_user: "{{ host_item['output_host_os_user'] }}"
        ansible_ssh_private_key_file: "{{ sap_vm_provision_terraform_work_dir_path }}/ssh/hosts_rsa"
        ansible_ssh_common_args: >-
          {{ sap_vm_provision_ssh_host_ssh_args }}
          -o ProxyCommand='ssh -W %h:%p
          {{ terraform_output.outputs['bastion_os_user'].value }}@{{ terraform_output.outputs['sap_vm_provision_bastion_public_ip'].value }}
          -p {{ terraform_output.outputs['bastion_port'].value }} -i {{ sap_vm_provision_terraform_work_dir_path }}/ssh/bastion_rsa
          {{ sap_vm_provision_ssh_bastion_ssh_args }}'
      loop: "{{ terraform_output.outputs['sap_host_list'].value }}"
      loop_control:
        loop_var: host_item
      register: __sap_vm_provision_register_terraform_add_hosts
      no_log: "{{ __sap_vm_provision_no_log }}"
      vars:
        # even skipped tasks register variables, so we need to choose one explicitly
        terraform_output: "{{
          (__sap_vm_provision_register_terraform_output_project_path is defined and __sap_vm_provision_register_terraform_output_project_path is success)
            | ternary(__sap_vm_provision_register_terraform_output_project_path, terraform_output_state_file) }}"
      when: sap_vm_provision_terraform_state == "present"


    - name: SAP VM Provision - AWS - Set fact to hold all inventory hosts in all groups
      ansible.builtin.set_fact:
        __sap_vm_provision_fact_merged_hosts_list: "{{
            [[groups[sap_vm_provision_group_hana_primary] | d([])],
            [groups[sap_vm_provision_group_hana_secondary] | d([])],
            [groups[sap_vm_provision_group_anydb_primary] | d([])],
            [groups[sap_vm_provision_group_anydb_secondary] | d([])],
            [groups[sap_vm_provision_group_nwas_ascs] | d([])],
            [groups[sap_vm_provision_group_nwas_ers] | d([])],
            [groups[sap_vm_provision_group_nwas_pas] | d([])],
            [groups[sap_vm_provision_group_nwas_aas] | d([])]] | flatten | select() }}"

    - name: SAP VM Provision - AWS - Set facts for all hosts - use facts from localhost for NFS
      delegate_to: "{{ host_item }}"
      delegate_facts: true
      ansible.builtin.set_fact:
        sap_vm_provision_nfs_mount_point: "{{ terraform_output.outputs['sap_vm_provision_nfs_mount_point'].value | default('') }}"
        sap_vm_provision_nfs_mount_point_separate_sap_transport_dir:
          "{{ terraform_output.outputs['sap_vm_provision_nfs_mount_point_separate_sap_transport_dir'].value | default('') }}"
        sap_vm_provision_nfs_mount_point_type: "{{ terraform_output.outputs['sap_vm_provision_nfs_mount_point_type'].value | default('') }}"
        sap_vm_provision_nfs_mount_point_opts: "{{ terraform_output.outputs['sap_vm_provision_nfs_mount_point_opts'].value | default('') }}"
      loop: "{{ __sap_vm_provision_fact_merged_hosts_list }}"
      loop_control:
        loop_var: host_item
      vars:
        # even skipped tasks register variables, so we need to choose one explicitly
        terraform_output: "{{
          (__sap_vm_provision_register_terraform_output_project_path is defined and __sap_vm_provision_register_terraform_output_project_path is success)
            | ternary(__sap_vm_provision_register_terraform_output_project_path, terraform_output_state_file) }}"
      when: sap_vm_provision_terraform_state == "present"

    # host_specifications_dictionary was used by 'set_ansible_vars_storage', but it now uses '__sap_vm_provision_host_dict_spec' instead.
    # - name: SAP VM Provision - AWS - Set facts for all hosts - use facts from localhost for host specification dictionary
    #   delegate_to: "{{ host_item }}"
    #   delegate_facts: true
    #   ansible.builtin.set_fact:
    #     host_specifications_dictionary: "{{ lookup('ansible.builtin.vars', __sap_vm_provision_host_spec_dict_name) }}"
    #   loop: "{{ __sap_vm_provision_fact_merged_hosts_list }}"
    #   loop_control:
    #     loop_var: host_item
    #   vars:
    #     # even skipped tasks register variables, so we need to choose one explicitly
    #     terraform_output: "{{
    #       (__sap_vm_provision_register_terraform_output_project_path is defined and __sap_vm_provision_register_terraform_output_project_path is success)
    #         | ternary(__sap_vm_provision_register_terraform_output_project_path, terraform_output_state_file) }}"
    #   when: sap_vm_provision_terraform_state == "present"


    - name: SAP VM Provision - AWS - Identify hosts
      ansible.builtin.include_tasks:
        file: common/identify_hosts.yml
      args:
        apply:
          delegate_to: "{{ host_item }}"
      run_once: true # Otherwise tasks will run twice per host
      loop: "{{ __sap_vm_provision_fact_merged_hosts_list }}"
      loop_control:
        loop_var: host_item

    - name: SAP VM Provision - AWS - Set Ansible Vars
      ansible.builtin.include_tasks:
        file: common/set_ansible_vars.yml
      args:
        apply:
          delegate_to: "{{ host_item }}"
      run_once: true # Otherwise tasks will run twice per host
      loop: "{{ __sap_vm_provision_fact_merged_hosts_list }}"
      loop_control:
        loop_var: host_item

    # Required to collect the remote host's facts for further processing in the following steps.
    # Collected facts can be used for all conditional tasks on provisioned hosts like ansible_facts['os_family'].
    - name: SAP VM Provision - AWS - Gather host facts
      delegate_to: "{{ host_item }}"
      delegate_facts: true
      ansible.builtin.setup:
      loop: "{{ __sap_vm_provision_fact_merged_hosts_list }}"
      loop_control:
        loop_var: host_item

    # Must be set to short hostname,
    # so that command 'hostname' and 'hostname -s' return the short hostname only;
    # otherwise may cause error with SAP SWPM using name.domain.com.domain.com
    - name: SAP VM Provision - AWS - Change system hostname (must be set to short name and not FQDN, as required by SAP)
      delegate_to: "{{ host_item }}"
      delegate_facts: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname_short }}"
      loop: "{{ __sap_vm_provision_fact_merged_hosts_list }}"
      loop_control:
        loop_var: host_item

    - name: SAP VM Provision - AWS - Set /etc/hosts
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts.yml
      args:
        apply:
          delegate_to: "{{ host_item }}"
      run_once: true # Otherwise tasks will run twice per host
      loop: "{{ __sap_vm_provision_fact_merged_hosts_list }}"
      loop_control:
        loop_var: host_item

    - name: SAP VM Provision - AWS - Set /etc/hosts for HA
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts_ha.yml
      when:
        - __sap_vm_provision_fact_is_ha_hana or __sap_vm_provision_fact_is_ha_anydb or __sap_vm_provision_fact_is_ha_nwas_ers
      args:
        apply:
          delegate_to: "{{ host_item }}"
      run_once: true # Otherwise tasks will run twice per host
      loop: "{{ __sap_vm_provision_fact_merged_hosts_list }}"
      loop_control:
        loop_var: host_item

    - name: SAP VM Provision - AWS - Set /etc/hosts for Scale-Out
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts_scaleout.yml
      when: __sap_vm_provision_fact_is_hana_scaleout
      args:
        apply:
          delegate_to: "{{ host_item }}"
      run_once: true # Otherwise tasks will run twice per host
      loop: "{{ __sap_vm_provision_fact_merged_hosts_list }}"
      loop_control:
        loop_var: host_item

    - name: SAP VM Provision - AWS - Set vars for sap_storage_setup Ansible Role
      ansible.builtin.include_tasks:
        file: common/set_ansible_vars_storage.yml
      when: sap_vm_provision_terraform_state == "present"
