# SPDX-License-Identifier: Apache-2.0
---

# Define listening port based on target host group. Same ports are used by sap_vm_provision during NLB creation
# 55550 - SAP HANA and SAP AnyDB
# 55551 - SAP SAP NetWeaver ASCS
# 55552 - SAP NetWeaver ERS
# Else returns 'UNSUPPORTED', because we cannot rely on consistent result.
# Reason: Ansible 2.16 returns type AnsibleUnsafeText while Ansible 2.20 returns type NoneType.

- name: SAP VM VIP - Set fact for temporary listening port
  ansible.builtin.set_fact:
    __sap_vm_temp_vip_fact_port: >-
      {%- if groups[sap_vm_temp_vip_group_hana_secondary] | d([]) | length > 0 and inventory_hostname in groups[sap_vm_temp_vip_group_hana_primary] -%}
        55550
      {%- elif groups[sap_vm_temp_vip_group_anydb_secondary] | d([]) | length > 0 and inventory_hostname in groups[sap_vm_temp_vip_group_anydb_primary] -%}
        55550
      {%- elif groups[sap_vm_temp_vip_group_nwas_ers] | d([]) | length > 0 and inventory_hostname in groups[sap_vm_temp_vip_group_nwas_ascs] -%}
        55551
      {%- elif groups[sap_vm_temp_vip_group_nwas_ers] | d([]) | length > 0 and inventory_hostname in groups[sap_vm_temp_vip_group_nwas_ers] -%}
        55552
      {%- else -%}UNSUPPORTED{%- endif -%}


# Check if defined port is already active and listening
# ss is used as it is present on both SUSE and Red Hat OS without need to install lsof or netstat
- name: SAP VM VIP - Check if temporary port is already open
  ansible.builtin.command:
    cmd: ss -tulnH "sport = :{{ __sap_vm_temp_vip_fact_port }}"
  register: __sap_vm_temp_vip_register_port_check
  when:
    - __sap_vm_temp_vip_fact_port != 'UNSUPPORTED'
    - __sap_vm_temp_vip_fact_port | trim | length > 0
  changed_when: false


- name: Block to start temporary netcat processes for Load Balancer Health Checks
  when:
    - __sap_vm_temp_vip_fact_port != 'UNSUPPORTED'
    - __sap_vm_temp_vip_fact_port | trim | length > 0
    - __sap_vm_temp_vip_register_port_check.stdout is defined
    - __sap_vm_temp_vip_register_port_check.stdout | length == 0
    - __sap_vm_temp_vip_fact_prefix | trim | length > 0  # Don't execute if prefix was empty during VIP creation
  block:

    # Get content of ip address show filtered by VIP - Additional execution if VIP was previously created
    - name: SAP VM VIP - Check if VIP is was already attached to network interface
      ansible.builtin.shell:
        cmd: "set -o pipefail && ip --oneline address show | grep {{ __sap_vm_temp_vip_fact_address }}/{{ __sap_vm_temp_vip_fact_prefix }}"
        executable: /bin/bash
      register: __sap_vm_temp_vip_register_check_ip
      changed_when: false
      ignore_errors: true
      failed_when: false

    # Install netcat package that is used to temporarily listen on ports
    - name: SAP VM VIP - Install netcat package
      ansible.builtin.package:
        name:
          - "{{ 'netcat' if ansible_facts['os_family'] == 'Suse' else 'nc' }}"
        state: present
      when:
        - __sap_vm_temp_vip_register_check_ip.stdout is defined
        - __sap_vm_temp_vip_register_check_ip.stdout | length > 0


    # Start netcat with timeout of 12 hours to ensure that SAP installation has enough time to complete.
    - name: SAP VM VIP - Start temporary 12 hour netcat process for Load Balancer Health Checks during SAP installation
      ansible.builtin.shell:
        cmd: >-
          nohup timeout 12h bash -c "while true; do nc -vvv -l -k {{ __sap_vm_temp_vip_fact_port }} ; done" </dev/null >/dev/null 2>&1 &
      changed_when: true
      when:
        - __sap_vm_temp_vip_register_check_ip.stdout is defined
        - __sap_vm_temp_vip_register_check_ip.stdout | length > 0
