# SPDX-License-Identifier: Apache-2.0
---

- name: Redhat OCP Virt - Print network
  ansible.builtin.debug:
    var: __sap_hypervisor_node_preconfigure_worker_network_item

# Reason for noqa: Name consists of multiline string with multiple long variables.
- name: "Redhat OCP Virt - Create NodeNetworkConfigurationPolicy \
         {{ __sap_hypervisor_node_preconfigure_worker_network_item.name }} on \
         {{ __sap_hypervisor_node_preconfigure_worker_item.name }}"  # noqa name[template]
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: nmstate.io/v1
      kind: NodeNetworkConfigurationPolicy
      metadata:
        name: "{{ __sap_hypervisor_node_preconfigure_worker_network_item.name }}-{{ __sap_hypervisor_node_preconfigure_worker_item.name }}"
      spec:
        nodeSelector:
          kubernetes.io/hostname: "{{ __sap_hypervisor_node_preconfigure_worker_item.name }}"
        desiredState:
          interfaces:
            - "{{ __sap_hypervisor_node_preconfigure_worker_network_item }}"
  when:
    - __sap_hypervisor_node_preconfigure_worker_network_item.type is defined
    - __sap_hypervisor_node_preconfigure_worker_network_item.type == 'linux-bridge'
      or __sap_hypervisor_node_preconfigure_worker_network_item.type == 'ethernet'
      or __sap_hypervisor_node_preconfigure_worker_network_item.type == 'vlan'

- name: Redhat OCP Virt - Create NetworkAttachmentDefinition {{ __sap_hypervisor_node_preconfigure_worker_network_item.name }}
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: "k8s.cni.cncf.io/v1"
      kind: NetworkAttachmentDefinition
      metadata:
        namespace: "{{ sap_hypervisor_node_preconfigure_cluster_config.vm_namespace }}"
        name: "{{ __sap_hypervisor_node_preconfigure_worker_network_item.name }}-network-definition"
        annotations:
          k8s.v1.cni.cncf.io/resourceName: "bridge.network.kubevirt.io/{{ __sap_hypervisor_node_preconfigure_worker_network_item.name }}"
      spec:
        config: "{{
          {'cniVersion': '0.3.1',
            'name': __sap_hypervisor_node_preconfigure_worker_network_item.name,
            'type': 'cnv-bridge',
            'bridge': __sap_hypervisor_node_preconfigure_worker_network_item.name,
            'macspoofchk': true} | to_json }}"
  when:
    - __sap_hypervisor_node_preconfigure_worker_network_item.type is defined
    - __sap_hypervisor_node_preconfigure_worker_network_item.type == 'linux-bridge'

- name: Redhat OCP Virt - Label the node with feature.node.kubernetes.io/network-sriov.capable=true
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ __sap_hypervisor_node_preconfigure_worker_item.name }}"
        labels:
          feature.node.kubernetes.io/network-sriov.capable: "true"
    state: present
  when:
    - __sap_hypervisor_node_preconfigure_worker_network_item.type is defined
    - __sap_hypervisor_node_preconfigure_worker_network_item.type == 'sriov'

# Reason for noqa: Name consists of multiline string with multiple long variables.
- name: "Redhat OCP Virt - Create SR-IOV NodeNetworkConfigurationPolicy \
         {{ __sap_hypervisor_node_preconfigure_worker_network_item.name }} on \
         {{ __sap_hypervisor_node_preconfigure_worker_item.name }}"  # noqa name[template]
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovNetworkNodePolicy
      metadata:
        name: "iface-{{ __sap_hypervisor_node_preconfigure_worker_network_item.name }}-sriov-{{ __sap_hypervisor_node_preconfigure_worker_item.name }}"
        namespace: openshift-sriov-network-operator
      spec:
        resourceName: "iface{{ __sap_hypervisor_node_preconfigure_worker_network_item.name }}sriov"
        nodeSelector:
          feature.node.kubernetes.io/network-sriov.capable: "true"
          kubernetes.io/hostname: "{{ __sap_hypervisor_node_preconfigure_worker_item.name }}"
        priority: 5
        mtu: 9000
        numVfs: 8
        nicSelector:
          pfNames: ['{{ __sap_hypervisor_node_preconfigure_worker_network_item.interface }}#0-7']
        deviceType: vfio-pci
        isRdma: false
  when:
    - __sap_hypervisor_node_preconfigure_worker_network_item.type is defined
    - __sap_hypervisor_node_preconfigure_worker_network_item.type == "sriov"

- name: Redhat OCP Virt - Create SriovNetwork Attachment Definition {{ __sap_hypervisor_node_preconfigure_worker_network_item.name }}
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovNetwork
      metadata:
        name: "iface-{{ __sap_hypervisor_node_preconfigure_worker_network_item.name }}-sriov"
        namespace: openshift-sriov-network-operator
      spec:
        ipam: |
          {
            "type": "host-local",
            "subnet": "192.168.1.0/24",
            "rangeStart": "192.168.1.200",
            "rangeEnd": "192.168.1.210"
          }
        networkNamespace: openshift-sriov-network-operator
        resourceName: "iface{{ __sap_hypervisor_node_preconfigure_worker_network_item.name }}sriov"
        spoofChk: "off"
        trust: "on"
  when:
    - __sap_hypervisor_node_preconfigure_worker_network_item.type is defined
    - __sap_hypervisor_node_preconfigure_worker_network_item.type == "sriov"
