# SPDX-License-Identifier: Apache-2.0
---

- name: Redhat OCP Virt - Include node network
  ansible.builtin.include_tasks:
    file: node-network.yml
  loop: "{{ __sap_hypervisor_node_preconfigure_worker_item.networks }}"
  loop_control:
    loop_var: __sap_hypervisor_node_preconfigure_worker_network_item
  when: __sap_hypervisor_node_preconfigure_worker_item.networks is defined
