# SPDX-License-Identifier: Apache-2.0
---

# Use vmware.vmware_rest Ansible Collection for VMware vCenter REST API, for VMware vSphere 7.0.2+
# Does not use community.vmware Ansible Collection for legacy pyvmomi Python Package for VMware vCenter SOAP API

- name: Ansible Task block for looped provisioning of VMware VMs
  any_errors_fatal: true
  block:

    - name: SAP VM Provision - VMware - Provision hosts to VMware vSphere
      ansible.builtin.include_tasks:
        file: "{{ __sap_vm_provision_task_file }}/execute_provision.yml"
        # apply:
        #   environment:
        #     VMWARE_HOST: "{{ sap_vm_provision_vmware_vcenter_hostname | d(lookup('env', 'VMWARE_HOST')) | d(omit) }}"
        #     VMWARE_VALIDATE_CERTS: "{{ (sap_vm_provision_vmware_vcenter_validate_certs_bool | d(lookup('env', 'VMWARE_VALIDATE_CERTS'))) | bool | d(false) }}"
        #     VMWARE_USER: "{{ sap_vm_provision_vmware_vcenter_user | d(lookup('env', 'VMWARE_USER')) | d(omit) }}"
        #     VMWARE_PASSWORD: "{{ sap_vm_provision_vmware_vcenter_password | d(lookup('env', 'VMWARE_PASSWORD')) | d(omit) }}"

    - name: SAP VM Provision - VMware - Set fact when using Bastion SSH Proxy connection from Ansible control node to target node/s
      ansible.builtin.set_fact:
        __sap_vm_provision_fact_ssh_args_bastion: >-
          -o ProxyCommand='ssh -W %h:%p {{ sap_vm_provision_bastion_user }}@{{ sap_vm_provision_bastion_public_ip }}
          -p {{ sap_vm_provision_bastion_ssh_port }}
          -i {{ sap_vm_provision_ssh_bastion_private_key_file_path }}
          {{ sap_vm_provision_ssh_bastion_ssh_args }}'
      when:
        - sap_vm_provision_bastion_execution
        - sap_vm_provision_bastion_user | d('') != ''
        - sap_vm_provision_bastion_public_ip | d('') != ''
        - sap_vm_provision_bastion_ssh_port | d('') != ''
        - sap_vm_provision_ssh_bastion_private_key_file_path | d('') != ''

    - name: SAP VM Provision - VMware - Add hosts provisioned to the Ansible Inventory
      ansible.builtin.add_host:
        name: "{{ add_item[0].host_node }}"
        groups: "{{ add_item[0].sap_system_type + '_' if (add_item[0].sap_system_type != '') }}{{ add_item[0].sap_host_type }}"
        ansible_host: "{{ add_item[0].__sap_vm_provision_register_gather_subset.ansible_facts.ansible_default_ipv4.address }}"
        ansible_user: "root"
        ansible_ssh_private_key_file: "{{ sap_vm_provision_ssh_host_private_key_file_path }}"
        ansible_ssh_common_args: "{{ sap_vm_provision_ssh_host_ssh_args }} {{ __sap_vm_provision_fact_ssh_args_bastion | d('') }}"
      loop: "{{ ansible_play_hosts | map('extract', hostvars, '__sap_vm_provision_fact_provisioned_hosts') }}"
      loop_control:
        label: "{{ add_item[0].host_node }}"
        loop_var: add_item
      register: __sap_vm_provision_register_provision_host_all_add
      no_log: "{{ __sap_vm_provision_no_log }}"


    - name: SAP VM Provision - VMware - Set fact to hold all inventory hosts in all groups
      ansible.builtin.set_fact:
        __sap_vm_provision_fact_merged_hosts_list: "{{
            [[groups[sap_vm_provision_group_hana_primary] | d([])],
            [groups[sap_vm_provision_group_hana_secondary] | d([])],
            [groups[sap_vm_provision_group_anydb_primary] | d([])],
            [groups[sap_vm_provision_group_anydb_secondary] | d([])],
            [groups[sap_vm_provision_group_nwas_ascs] | d([])],
            [groups[sap_vm_provision_group_nwas_ers] | d([])],
            [groups[sap_vm_provision_group_nwas_pas] | d([])],
            [groups[sap_vm_provision_group_nwas_aas] | d([])]] | flatten | select() }}"


    - name: SAP VM Provision - VMware - Identify hosts
      ansible.builtin.include_tasks:
        file: common/identify_hosts.yml

    - name: SAP VM Provision - VMware - Set Ansible Vars
      ansible.builtin.include_tasks:
        file: common/set_ansible_vars.yml

  rescue:
    # This requires no_log set on each Ansible Task, and not set on the Ansible Task Block
    # This requires an Ansible Task Block containing the Ansible Tasks for calling
    # Infrastructure Platform APIs (via Ansible Modules)
    - name: SAP VM Provision - VMware - Show errors in task outputs
      ansible.builtin.fail:
        msg: "{{ lookup('ansible.builtin.vars', loop_item) }}"
      loop:
        # Main
        - __sap_vm_provision_register_provision_host_all_add
        # Provision
        - __sap_vm_provision_register_vmware_vm_folder
        - __sap_vm_provision_register_vmware_vm_cluster
        - __sap_vm_provision_register_vmware_vm_cluster_host
        - __sap_vm_provision_register_vmware_vm_cluster_datastore
        - __sap_vm_provision_register_vmware_vm_content_library
        - __sap_vm_provision_register_vmware_vm_content_library_items
        - __sap_vm_provision_register_provision_host_single_check_exists
        - __sap_vm_provision_register_provision_host_single
        - __sap_vm_provision_register_provision_host_single_info
        - __sap_vm_provision_register_vmware_vm_guest_customization
        - __sap_vm_provision_register_vmware_vm_power_info
        - __sap_vm_provision_register_vmware_vm_info
        - __sap_vm_provision_register_vmware_vm_nic_info
        - __sap_vm_provision_register_gather_subset
        - __sap_vm_provision_register_provision_host_single_volumes
      loop_control:
        loop_var: loop_item
        index_var: loop_item_index
        label: "{{ 'Variable No. ' + (loop_item_index | string) }}"
      when:
        - lookup('ansible.builtin.vars', loop_item, default='') | length > 0
        - not lookup('ansible.builtin.vars', loop_item, default='') is skipped
        - lookup('ansible.builtin.vars', loop_item, default='') is failed

    - name: SAP VM Provision - VMware - Fail if provisioning failed
      ansible.builtin.fail:
        msg: |
          FAIL: Provisioning has failed during one of tasks not producing registered output.
          You can investigate failure in tasks above or by:
          - Increasing verbosity
          - Setting the variable '__sap_vm_provision_no_log' to 'false'


- name: Ansible Task block to execute on target inventory hosts
  delegate_to: "{{ inventory_hostname }}"
  block:

    # Required to collect the remote host's facts for further processing in the following steps.
    # Collected facts can be used for all conditional tasks on provisioned hosts like ansible_facts['os_family'].
    - name: SAP VM Provision - VMware - Gather host facts
      ansible.builtin.setup:

    # Must be set to short hostname,
    # so that command 'hostname' and 'hostname -s' return the short hostname only;
    # otherwise may cause error with SAP SWPM using name.domain.com.domain.com
    - name: SAP VM Provision - VMware - Change system hostname (must be set to short name and not FQDN, as required by SAP)
      ansible.builtin.hostname:
        name: "{{ inventory_hostname_short }}"

    - name: SAP VM Provision - VMware - Set /etc/hosts
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts.yml

    - name: SAP VM Provision - VMware - Set /etc/hosts for HA
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts_ha.yml
      when:
        - __sap_vm_provision_fact_is_ha_hana or __sap_vm_provision_fact_is_ha_anydb or __sap_vm_provision_fact_is_ha_nwas_ers

    - name: SAP VM Provision - VMware - Set /etc/hosts for Scale-Out
      ansible.builtin.include_tasks:
        file: common/set_etc_hosts_scaleout.yml
      when: __sap_vm_provision_fact_is_hana_scaleout

    - name: SAP VM Provision - VMware - Set vars for sap_storage_setup Ansible Role
      ansible.builtin.include_tasks:
        file: common/set_ansible_vars_storage.yml

    - name: SAP VM Provision - VMware - Register Web Forward Proxy
      ansible.builtin.include_tasks:
        file: common/register_proxy.yml

    - name: SAP VM Provision - VMware - Register Package Repositories
      ansible.builtin.include_tasks:
        file: common/register_os.yml
