# SPDX-License-Identifier: Apache-2.0
---

- name: Redhat OCP Virt - Create the SR-IOV Operator namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-sriov-network-operator

- name: Redhat OCP Virt - Create the SR-IOV Operator namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: sriov-network-operators
        namespace: openshift-sriov-network-operator
      spec:
        targetNamespaces:
          - openshift-sriov-network-operator

- name: Redhat OCP Virt - Create the SR-IOV Operator namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: sriov-network-operator-subscription
        namespace: openshift-sriov-network-operator
      spec:
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        name: sriov-network-operator
        channel: "stable"

- name: Redhat OCP Virt - Wait for Subscription to have an InstallPlan
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: sriov-network-operator-subscription
    namespace: openshift-sriov-network-operator
  register: __sap_hypervisor_node_preconfigure_register_subscription_status
  retries: 30
  delay: 10
  until: __sap_hypervisor_node_preconfigure_register_subscription_status.resources[0].status.installplan.name is defined

# Reason for noqa: Ignore errors during retry loop and fail in subsequent task.
- name: Redhat OCP Virt - Wait for InstallPlan to complete for SR-IOV  # noqa: ignore-errors
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: "{{ __sap_hypervisor_node_preconfigure_register_subscription_status.resources[0].status.installplan.name }}"
    namespace: openshift-sriov-network-operator
  register: __sap_hypervisor_node_preconfigure_register_installplan_status
  retries: 30
  delay: 10
  ignore_errors: true
  until: __sap_hypervisor_node_preconfigure_register_installplan_status.resources[0].status.phase == "Complete"

- name: Redhat OCP Virt - Verify SR-IOV Operator is running
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    name: sriov-network-operators
    namespace: openshift-sriov-network-operator
  register: __sap_hypervisor_node_preconfigure_register_operatorgroup_status
  retries: 30
  delay: 10
  until: __sap_hypervisor_node_preconfigure_register_operatorgroup_status.resources | d([]) | length > 0

# Reason for noqa: Ignore errors during retry loop and fail in subsequent task.
- name: Redhat OCP Virt - Check if SriovOperatorConfig exists  # noqa: ignore-errors
  kubernetes.core.k8s_info:
    api_version: sriovnetwork.openshift.io/v1
    kind: SriovOperatorConfig
    name: default
    namespace: openshift-sriov-network-operator
  register: __sap_hypervisor_node_preconfigure_register_sriov_operator_config_status
  ignore_errors: true

- name: Redhat OCP Virt - Enable unsupported NICs for SR-IOV usage if the resource exists
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovOperatorConfig
      metadata:
        name: default
        namespace: openshift-sriov-network-operator
      spec:
        enableOperatorWebhook: false
  when: __sap_hypervisor_node_preconfigure_register_sriov_operator_config_status.resources | d([]) | length > 0

- name: Redhat OCP Virt - Create SriovOperatorConfig if it does not exist
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovOperatorConfig
      metadata:
        name: default
        namespace: openshift-sriov-network-operator
      spec:
        disableDrain: false
        enableInjector: true
        enableOperatorWebhook: false
        logLevel: 2

- name: Redhat OCP Virt - Wait for SriovOperatorConfig to exist
  kubernetes.core.k8s_info:
    api_version: sriovnetwork.openshift.io/v1
    kind: SriovOperatorConfig
    name: default
    namespace: openshift-sriov-network-operator
  register: __sap_hypervisor_node_preconfigure_register_sriov_operator_config_status
  retries: 10
  delay: 10
  until: __sap_hypervisor_node_preconfigure_register_sriov_operator_config_status.resources | d([]) | length > 0
