# SPDX-License-Identifier: Apache-2.0
---

- name: Redhat OCP Virt - Include install CNV operator
  ansible.builtin.include_tasks:
    file: "platform/{{ sap_hypervisor_node_preconfigure_platform }}/operators/install-cnv-operator.yml"

- name: Redhat OCP Virt - Include install sriov operator
  ansible.builtin.include_tasks:
    file: "platform/{{ sap_hypervisor_node_preconfigure_platform }}/operators/install-sriov-operator.yml"

- name: Redhat OCP Virt - Include install nmstate operator
  ansible.builtin.include_tasks:
    file: "platform/{{ sap_hypervisor_node_preconfigure_platform }}/operators/install-nmstate-operator.yml"
