# SPDX-License-Identifier: Apache-2.0
---

- name: Redhat RHEL KVM - Get kernel command line
  ansible.builtin.command:
    cmd: cat /proc/cmdline
  register: __sap_hypervisor_node_preconfigure_register_kernelcmdline_assert
  changed_when: __sap_hypervisor_node_preconfigure_register_kernelcmdline_assert.rc != 0

# Reason for noqa: Ignore errors because command does not produce compatible return codes.
- name: Redhat RHEL KVM - Assert - Kernel same page merging (KSM) - Get status  # noqa: ignore-errors
  ansible.builtin.command:
    cmd: systemctl status ksm
  register: __sap_hypervisor_node_preconfigure_register_ksmstatus_assert
  ignore_errors: true
  changed_when: __sap_hypervisor_node_preconfigure_register_ksmstatus_assert.rc != 0

- name: Redhat RHEL KVM - Assert - Kernel same page merging (KSM) - Check if stopped
  ansible.builtin.assert:
    that: "'Active: inactive (dead)' in __sap_hypervisor_node_preconfigure_register_ksmstatus_assert.stdout"
    fail_msg: "FAIL: ksm is running"
    success_msg: "PASS: ksm not running"
  when: not sap_hypervisor_node_preconfigure_ignore_failed_assertion


# Reason for noqa: Ignore errors because command does not produce compatible return codes.
- name: Redhat RHEL KVM - Assert - Kernel same page merging (KSM) Tuning Daemon - Get status  # noqa: ignore-errors
  ansible.builtin.command:
    cmd: systemctl status ksmtuned
  register: __sap_hypervisor_node_preconfigure_register_ksmtunedstatus_assert
  ignore_errors: true
  changed_when: __sap_hypervisor_node_preconfigure_register_ksmtunedstatus_assert.rc != 0

- name: Redhat RHEL KVM - Assert - Kernel same page merging (KSM) Tuning Daemon - Check if stopped
  ansible.builtin.assert:
    that: "'Active: inactive (dead)' in __sap_hypervisor_node_preconfigure_register_ksmtunedstatus_assert.stdout"
    fail_msg: "FAIL: ksmtuned is running"
    success_msg: "PASS: ksmtuned not running"
  when: not sap_hypervisor_node_preconfigure_ignore_failed_assertion


- name: Redhat RHEL KVM - Check CPU Stepping
  ansible.builtin.shell:
    cmd: set -o pipefail && lscpu | awk '/Stepping/{print $2}'
  register: __sap_hypervisor_node_preconfigure_register_cpu_stepping_output_assert
  changed_when: __sap_hypervisor_node_preconfigure_register_cpu_stepping_output_assert.rc != 0

- name: Redhat RHEL KVM - Register stepping as fact
  ansible.builtin.set_fact:
    __sap_hypervisor_node_preconfigure_fact_cpu_stepping_assert:
      "{{ __sap_hypervisor_node_preconfigure_register_cpu_stepping_output_assert.stdout }}"

- name: Redhat RHEL KVM - Print CPU Stepping
  ansible.builtin.debug:
    var: __sap_hypervisor_node_preconfigure_fact_cpu_stepping_assert

# skylake:
- name: Block for Intel Skylake CPU Platform
  when: __sap_hypervisor_node_preconfigure_fact_cpu_stepping_assert == "4"
  block:
    # Reason for noqa: Ignore errors because command does not produce compatible return codes.
    - name: Redhat RHEL KVM - Get ple_gap  # noqa: ignore-errors
      ansible.builtin.command:
        cmd: grep -E '^options\s+kvm_intel.*?ple_gap\s*=\s*0.*$' /etc/modprobe.d/kvm.conf
      register: __sap_hypervisor_node_preconfigure_register_skylake_plegap_assert
      ignore_errors: true
      changed_when: __sap_hypervisor_node_preconfigure_register_skylake_plegap_assert.rc != 0

    - name: Redhat RHEL KVM - Assert - Check if ple_gap=0
      ansible.builtin.assert:
        that: "__sap_hypervisor_node_preconfigure_register_skylake_plegap_assert.rc == 0"
        fail_msg: "FAIL: ple_gap is not set to 0"
        success_msg: "PASS: ple_gap is set to 0"
      when: not sap_hypervisor_node_preconfigure_ignore_failed_assertion

    - name: Redhat RHEL KVM - Assert - Check for spectre_v2=retpoline
      ansible.builtin.assert:
        that: "'spectre_v2=retpoline' in __sap_hypervisor_node_preconfigure_register_kernelcmdline_assert.stdout"
        fail_msg: "FAIL: spectre_v2=retpoline is not on Kernel command line"
        success_msg: "PASS: spectre_v2=retpoline is on Kernel command line"
      when: not sap_hypervisor_node_preconfigure_ignore_failed_assertion


- name: Redhat RHEL KVM - Assert - Check kvm.nx_huge_pages is {{ sap_hypervisor_node_preconfigure_kvm_nx_huge_pages | d('N/A') }}
  ansible.builtin.assert:
    that: __nx_huge_pages == sap_hypervisor_node_preconfigure_kvm_nx_huge_pages
    fail_msg: "FAIL: kvm.nx_huge_pages is not {{ sap_hypervisor_node_preconfigure_kvm_nx_huge_pages }}"
    success_msg: "PASS: kvm.nx_huge_pages is {{ sap_hypervisor_node_preconfigure_kvm_nx_huge_pages }}"
  vars:
    __nx_huge_pages:
      "{{ __sap_hypervisor_node_preconfigure_register_kernelcmdline_assert.stdout | regex_search('kvm.nx_huge_pages=(.+)', '\\1') | first }}"
  when:
    - sap_hypervisor_node_preconfigure_kvm_nx_huge_pages is defined
    - not sap_hypervisor_node_preconfigure_ignore_failed_assertion


- name: Assert - check seccomp_sandbox=0
  block:
    # Reason for noqa: Ignore errors because command does not produce compatible return codes.
    - name: Redhat RHEL KVM - Get seccomp setting  # noqa: ignore-errors
      ansible.builtin.command:
        cmd: grep -E '^seccomp_sandbox\s+=\s+0.*$' /etc/libvirt/qemu.conf
      register: __sap_hypervisor_node_preconfigure_register_seccomp_assert
      ignore_errors: true
      changed_when: __sap_hypervisor_node_preconfigure_register_seccomp_assert.rc != 0

    - name: "Redhat RHEL KVM - Assert - Check seccomp_sandbox=0 is in /etc/libvirt/qemu.conf"
      ansible.builtin.assert:
        that: __sap_hypervisor_node_preconfigure_register_seccomp_assert is success
        fail_msg: "FAIL: seccomp_sandbox != 0"
        success_msg: "PASS: seccomp_sanbox == 0"
      when: not sap_hypervisor_node_preconfigure_ignore_failed_assertion


- name: Assert - check amount of 1G hugepages
  block:
    - name: Redhat RHEL KVM - Get amount of 1G hugepages
      ansible.builtin.shell:
        cmd: set -o pipefail && hugeadm --pool-list | grep 1073741824 | awk '{print $3}'
      register: __sap_hypervisor_node_preconfigure_register_1g_hugepages_assert
      changed_when: __sap_hypervisor_node_preconfigure_register_1g_hugepages_assert.rc != 0

    - name: "Redhat RHEL KVM - Ensure hypervisor RAM and hugepages meet min requirement (GB) {{ sap_hypervisor_node_preconfigure_reserved_ram }}"
      ansible.builtin.assert:
        that: __available_mem >= __minimum_mem
        fail_msg: "FAIL: Not enough memory reserved for hypervisor"
        success_msg: "PASS: Enough memory reserved for hypervisor"
      vars:
        __available_mem: "{{ (ansible_facts['memtotal_mb'] / 1024) | int - sap_hypervisor_node_preconfigure_reserved_ram | int }}"
        __minimum_mem: "{{ __sap_hypervisor_node_preconfigure_register_1g_hugepages_assert.stdout | int }}"
      when: not sap_hypervisor_node_preconfigure_ignore_failed_assertion


- name: Assert - check Kernel command line
  block:
    - name: Redhat RHEL KVM - Ensure iommu is enabled
      ansible.builtin.assert:
        that: "'intel_iommu=on' in __sap_hypervisor_node_preconfigure_register_kernelcmdline_assert.stdout"
        fail_msg: "FAIL: intel_iommu=on not on Kernel command line"
        success_msg: "PASS: intel_iommu=on on Kernel command line"
      when: not sap_hypervisor_node_preconfigure_ignore_failed_assertion

    - name: Redhat RHEL KVM - Ensure iommu passthrough is enabled
      ansible.builtin.assert:
        that: "'iommu=pt' in __sap_hypervisor_node_preconfigure_register_kernelcmdline_assert.stdout"
        fail_msg: "FAIL: iommu=pt not on Kernel command line"
        success_msg: "PASS: iommu=pt on Kernel command line"
      when: not sap_hypervisor_node_preconfigure_ignore_failed_assertion

    # See SAP Note 2737837 - SAP HANA and the Intel Transactional Synchronization Extensions Capability
    - name: Redhat RHEL KVM - Ensure tsx is on
      ansible.builtin.assert:
        that: "'tsx=on' in __sap_hypervisor_node_preconfigure_register_kernelcmdline_assert.stdout"
        fail_msg: "FAIL: tsx=on not in Kernel command line"
        success_msg: "PASS: tsx=on in Kernel command line"
      when: not sap_hypervisor_node_preconfigure_ignore_failed_assertion
