# SPDX-License-Identifier: Apache-2.0
---

- name: Redhat RHEL KVM - Check file permissions {{ __sap_hypervisor_node_preconfigure_hook_item }}
  ansible.builtin.command:
    cmd: stat -c%a /usr/libexec/vdsm/hooks/before_vm_start/{{ __sap_hypervisor_node_preconfigure_hook_item }}
  register: __sap_hypervisor_node_preconfigure_register_file_permissions_assert
  changed_when: __sap_hypervisor_node_preconfigure_register_file_permissions_assert.rc != 0

- name: Redhat RHEL KVM - Assert hook file permissions {{ __sap_hypervisor_node_preconfigure_hook_item }}
  ansible.builtin.assert:
    that: "__sap_hypervisor_node_preconfigure_register_file_permissions_assert.stdout == '755'"
    fail_msg: "FAIL: Hook {{ __sap_hypervisor_node_preconfigure_hook_item }} does not have the correct file permissions (!= 755)."
    success_msg: "PASS: Hook {{ __sap_hypervisor_node_preconfigure_hook_item }} does have the correct file permissions (755)."
  when: not sap_hypervisor_node_preconfigure_ignore_failed_assertion


- name: Redhat RHEL KVM - Create tmp dir {{ __sap_hypervisor_node_preconfigure_hook_item }}
  ansible.builtin.file:
    path: /tmp/sap_hypervisor_node_preconfigure
    state: directory
    mode: "0755"

- name: Redhat RHEL KVM - Copy hook for checking {{ __sap_hypervisor_node_preconfigure_hook_item }}
  ansible.builtin.copy:
    dest: "/tmp/sap_hypervisor_node_preconfigure/{{ __sap_hypervisor_node_preconfigure_hook_item }}"
    src: "{{ __sap_hypervisor_node_preconfigure_hook_item }}"
    mode: "0755"

# Reason for noqa: Ignore errors because command does not produce compatible return codes.
- name: Redhat RHEL KVM - Diff hook  {{ __sap_hypervisor_node_preconfigure_hook_item }} # noqa: ignore-errors
  ansible.builtin.command:
    cmd: >-
      diff
      -uw /tmp/sap_hypervisor_node_preconfigure/{{ __sap_hypervisor_node_preconfigure_hook_item }}
      /usr/libexec/vdsm/hooks/before_vm_start/{{ __sap_hypervisor_node_preconfigure_hook_item }}"
  register: __sap_hypervisor_node_preconfigure_register_hook_diff_assert
  ignore_errors: true
  changed_when: __sap_hypervisor_node_preconfigure_register_hook_diff_assert.rc != 0

- name: Redhat RHEL KVM - Assert hook content {{ __sap_hypervisor_node_preconfigure_hook_item }}
  ansible.builtin.assert:
    that: "__sap_hypervisor_node_preconfigure_register_hook_diff_assert.rc == 0"
    fail_msg: "FAIL: Hook {{ __sap_hypervisor_node_preconfigure_hook_item }} has been modified, please investigate manually."
    success_msg: "PASS: Hook {{ __sap_hypervisor_node_preconfigure_hook_item }} not modified"
  when: not sap_hypervisor_node_preconfigure_ignore_failed_assertion
