# SPDX-License-Identifier: Apache-2.0
---

- name: Redhat RHEL KVM - Stop and disable kernel same page merging (KSM)
  ansible.builtin.systemd:
    name: ksm
    state: stopped
    enabled: false

- name: Redhat RHEL KVM - Stop and disable kernel same page merging (KSM) tuning daemon
  ansible.builtin.systemd:
    name: ksmtuned
    state: stopped
    enabled: false

- name: Redhat RHEL KVM - Check CPU Stepping
  ansible.builtin.shell:
    cmd: set -o pipefail && lscpu | awk '/Stepping/{print $2}'
  register: __sap_hypervisor_node_preconfigure_register_cpu_stepping_output
  changed_when: __sap_hypervisor_node_preconfigure_register_cpu_stepping_output.rc != 0

- name: Redhat RHEL KVM - Register CPU stepping as fact
  ansible.builtin.set_fact:
    __sap_hypervisor_node_preconfigure_register_cpu_stepping:
      "{{ __sap_hypervisor_node_preconfigure_register_cpu_stepping_output.stdout }}"

- name: Block for Intel Skylake CPU Platform
  become: true
  become_user: root
  when: __sap_hypervisor_node_preconfigure_register_cpu_stepping == "4"
  block:

    - name: Redhat RHEL KVM - Set ple_gap=0 on Intel Skylake CPU Platform
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/kvm.conf
        line: options kvm_intel ple_gap=0

    - name: Redhat RHEL KVM - Set spectre_v2=retpoline on Intel Skylake CPU Platform
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        backup: true
        backrefs: true
        state: present
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ grub_item }}).*). *$'
        line: "\\1 {{ grub_item }}\""
      loop:
        - "spectre_v2=retpoline"
      loop_control:
        loop_var: grub_item
      notify: __sap_hypervisor_node_preconfigure_regenerate_grub2_conf_handler
      tags: grubconfig
      become: true
      become_user: root


- name: Redhat RHEL KVM - Set kvm.nx_huge_pages to {{ sap_hypervisor_node_preconfigure_kvm_nx_huge_pages | d('N/A') }}
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    backrefs: true
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ grub_item }}).*). *$'
    line: "\\1 {{ grub_item }}\""
  loop:
    - "kvm.nx_huge_pages={{ sap_hypervisor_node_preconfigure_kvm_nx_huge_pages }}"
  loop_control:
    loop_var: grub_item
  notify: __sap_hypervisor_node_preconfigure_regenerate_grub2_conf_handler
  tags: grubconfig
  when: sap_hypervisor_node_preconfigure_kvm_nx_huge_pages is defined
  become: true
  become_user: root

- name: Redhat RHEL KVM - Set seccomp_sanbox=0
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    backup: true
    backrefs: true
    state: present
    regexp: 'seccomp_sandbox'
    line: "seccomp_sandbox = 0"
  become: true
  become_user: root

- name: Redhat RHEL KVM - Include allocate hughepages at runtime
  ansible.builtin.include_tasks:
    file: allocate-hugepages-at-runtime.yml
  when: sap_hypervisor_node_preconfigure_reserve_hugepages == "runtime"

- name: Redhat RHEL KVM - Reserve Hugepages statically
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    backrefs: true
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ grub_item }}).*). *$'
    line: "\\1 {{ grub_item }}\""
  loop:
    - default_hugepagesz=1GB
    - hugepagesz=1GB
    - hugepages={{ (ansible_facts['memtotal_mb'] / 1024) | int - sap_hypervisor_node_preconfigure_reserved_ram }}
  loop_control:
    loop_var: grub_item
  notify: __sap_hypervisor_node_preconfigure_regenerate_grub2_conf_handler
  tags: grubconfig
  when: sap_hypervisor_node_preconfigure_reserve_hugepages == "static"
  become: true
  become_user: root

- name: Redhat RHEL KVM - Enable IOMMU PT
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    backrefs: true
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ grub_item }}).*). *$'
    line: "\\1 {{ grub_item }}\""
  loop:
    - intel_iommu=on
    - iommu=pt
  loop_control:
    loop_var: grub_item
  notify: __sap_hypervisor_node_preconfigure_regenerate_grub2_conf_handler
  tags: grubconfig
  become: true
  become_user: root

# See SAP Note 2737837 - SAP HANA and the Intel Transactional Synchronization Extensions Capability
- name: Redhat RHEL KVM - Enable TSX
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    backrefs: true
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ grub_item }}).*). *$'
    line: "\\1 {{ grub_item }}\""
  loop:
    - "tsx={{ sap_hypervisor_node_preconfigure_tsx }}"
  loop_control:
    loop_var: grub_item
  notify: __sap_hypervisor_node_preconfigure_regenerate_grub2_conf_handler
  tags: grubconfig
  become: true
  become_user: root
