# SPDX-License-Identifier: Apache-2.0
---

- name: Block to set assert prefix
  vars:
    __prefix: "{{ 'assert-' if sap_hypervisor_node_preconfigure_assert | d(false) else '' }}"
  block:
    - name: Redhat RHEL KVM - Include the task file installation.yml
      ansible.builtin.include_tasks:
        file: '{{ __prefix }}installation.yml'

    - name: Redhat RHEL KVM - Include the task file configuration.yml
      ansible.builtin.include_tasks:
        file: '{{ __prefix }}configuration.yml'

    - name: Redhat RHEL KVM - Include the task file set-tuned-profile.yml
      ansible.builtin.include_tasks:
        file: '{{ __prefix }}set-tuned-profile.yml'

    - name: Redhat RHEL KVM - Include the task file rhv-hooks.yml
      ansible.builtin.include_tasks:
        file: "{{ __prefix }}rhv-hooks.yml"
      loop:
        - 50_hana
        - 50_iothread_pinning
      loop_control:
        loop_var: __sap_hypervisor_node_preconfigure_hook_item
